<center><span style="font-family:Didot; font-size:1.5em;">**Samuel Olson** </span></center>


<center><span style="font-family:Didot; font-size:1em;"> **Email:** [samuel.david.olson@gmail.com](samuel.david.olson@gmail.com) | **Github:** [samdolson](http://github.com/samdolson) | **LinkedIn:** [Samuel Olson](https://www.linkedin.com/in/samuel-olson-108b73135/)</span></center>

<center><span style="font-family:Didot; font-size:1em;"> **Phone:** +1(763)280-0544 | **Location:** Portland, OR USA </span></center>

------

<span style="font-family:Didot; font-size:1em ;"> <p align="left"> 

Recipient

Recipient Position

Recipient Company

Address

Town, State, Zip </p>

<p><br></p>

<span style="font-family:Didot; font-size:1em ;"> <p align="left">
Dear Mr./Mrs. X, 
<p><br></p>
Thank you for the opportunity to apply for the **XXX** position.
<p><br></p>
I have over $3 \frac{1}{2}$ years of research experience, both academic and professional. This experience has made be confident in pursuing independent as well as collaborative research. Though I have prior experience specifically in economics, forestry, marketing, customer service, and a number of other departments, I am open to pursuing new fields of research. 
<p><br></p>
I’ve conducted research in several different fields---economics, market research, and forestry—--using a variety of research methodologies. My skills include use of R, VBA, and Stata, as well as soft skills such as project management. I enjoy learning new use cases, programs, and packages. 
<p><br></p>
My goal is to continue building my research and analytical skills, and build new ones, as a research assistant. To further my skills, I just recently went back to my Alma Mater, Reed College to audit two statistics courses. One of these courses, Statistics Practicum, reinforced my desire to continue pursuing research through a semester-long group research project and additional coursework focused on learning more about various aspects of the research process. This opportunity reignited my desire to pursue academic research. 
<p><br></p>
Thank you for reviewing my qualifications for this exciting position.
<p><br></p>
Please feel free to contact me at via phone at +1(763)280-0544 or via email at samuel.david.olson@gmail.com. I am happy to provide references.
<p><br></p>
Sincerely,</p>
```{r fig.width=2, fig.height=1,echo=FALSE}
library(png)
library(grid)
img <- readPNG( "C:/Users/samue/Documents/Resumes_and_such/signature.png")
 grid.raster(img)
```
<p align="left"> Samuel Olson </p>  </span>