---
title: "Reference Knit Code"
output: html_document
---

Location: samue

# New Resume 2021
# Latest
"C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe" "file:///C:/Users/samue/Documents/Resumes_and_such/SDO_Resume_2021.html" SDO_Resume.pdf

# New Resume
"C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe" "file:///C:/Users/samue/Documents/Resumes_and_such/SDO_Resume.html" SDO_Resume.pdf

# General
"C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe" "file:///C:/Users/samue/Documents/Resumes_and_such/SDO_Res_Gen.html" SDO_Res_Gen.pdf

# Quant Washington
"C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe" "file:///C:/Users/samue/Documents/Resumes_and_such/WA_Quant.html" WA_Quant.pdf

"C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe" "file:///C:/Users/samue/Documents/Resumes_and_such/Resumes/WA_Secondary_Test.html" WA_Resume_Sam_D_Olson.pdf

# Michigan

"C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe" "file:///C:/Users/samue/Documents/Resumes_and_such/Resumes/MI_Secondary_Test.html" UMICH_Resume_Sam_D_Olson.pdf

"C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe" "file:///C:/Users/samue/Documents/Resumes_and_such/Resumes/MI_Course_Supp.html" U_M_Course_Supp.pdf

## Current

"C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe" "file:///C:/Users/samue/Documents/Resumes_and_such/Resumes/Secondary_Test.html" Resume_Sam_D_Olson.pdf

# General Course Overview
"C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe" "file:///C:/Users/samue/Documents/Resumes_and_such/Resumes/Course_Overview.html" Course_Overview_SDO.pdf

# Detailed Course Overview
"C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe" "file:///C:/Users/samue/Documents/Resumes_and_such/Resumes/Detailed_Course_Overview.html" Detailed_Course_Overview_SDO.pdf

# Personal Statement No Div
"C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe" "file:///C:/Users/samue/Documents/Resumes_and_such/Resumes/UW_Supplement.html" Supplement_SDO.pdf

# Madison-Wisc
## All
"C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe" "file:///C:/Users/samue/Documents/Resumes_and_such/Resumes/Course_Overview_Madison.html" Course_Overview_Quant_SDO.pdf

## Comp
"C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe" "file:///C:/Users/samue/Documents/Resumes_and_such/Resumes/Comp_Course_Overview_Madison.html" Comp_Course_Overview_SDO.pdf

Check

samue

## Yeet 

"C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe" https://google.com google.pdf

"C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe" "file:///C:/Users/samue/Documents/Resumes_and_such/Resume_Sam_D_Olson.html" example.pdf

"C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe" "file:///C:/Users/samue/Documents/Resumes_and_such/Resumes/Secondary_Test.html" Resume_Sam_D_Olson.pdf

"C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe" "file:///C:/Users/samue/Documents/Resumes_and_such/HTML_Testing.html" htmltest.pdf

"C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe" "file:///C:/Users/samue/Documents/Resumes_and_such/Cover-Letter.html" Cover_Letter.pdf